// =============================================================================
// TEST GENERATION
// =============================================================================

import { GeneratedFile, Gap, RepoContext } from '../types'

/**
 * Generate tests for identified gaps
 */
export async function generateTests(
  ctx: RepoContext,
  gaps: Gap[]
): Promise<GeneratedFile[]> {
  const files: GeneratedFile[] = []
  
  // Generate vitest setup if no test framework
  const noFramework = gaps.find(g => g.id === 'testing-no-framework')
  if (noFramework) {
    files.push(...generateVitestSetup())
  }
  
  // Generate playwright setup if no e2e
  const noE2E = gaps.find(g => g.id === 'testing-no-e2e')
  if (noE2E) {
    files.push(...generatePlaywrightSetup())
  }
  
  return files
}

/**
 * Generate Vitest configuration
 */
function generateVitestSetup(): GeneratedFile[] {
  return [{
    path: 'vitest.config.ts',
    content: `// =============================================================================
// VITEST CONFIGURATION
// =============================================================================
// Generated by Orion

import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'
import path from 'path'

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['./vitest.setup.ts'],
    include: ['**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}'],
    exclude: ['node_modules', 'dist', '.next', 'e2e'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      exclude: [
        'node_modules/**',
        'dist/**',
        '**/*.d.ts',
        'vitest.config.ts',
      ],
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './'),
    },
  },
})
`,
    language: 'typescript',
    category: 'testing',
    confidence: 95,
    description: 'Vitest configuration file',
  }, {
    path: 'vitest.setup.ts',
    content: `// =============================================================================
// VITEST SETUP
// =============================================================================
// Generated by Orion

import '@testing-library/jest-dom/vitest'

// Mock environment variables
process.env.NODE_ENV = 'test'
process.env.ENCRYPTION_SECRET = 'test-secret-key-minimum-32-characters-long'

// Mock next/navigation
vi.mock('next/navigation', () => ({
  useRouter: () => ({
    push: vi.fn(),
    replace: vi.fn(),
    prefetch: vi.fn(),
    back: vi.fn(),
  }),
  useSearchParams: () => new URLSearchParams(),
  usePathname: () => '/',
}))

// Mock next-auth
vi.mock('next-auth/react', () => ({
  useSession: () => ({ data: null, status: 'unauthenticated' }),
  signIn: vi.fn(),
  signOut: vi.fn(),
}))

// Global test utilities
declare global {
  // eslint-disable-next-line no-var
  var testUtils: {
    delay: (ms: number) => Promise<void>
  }
}

globalThis.testUtils = {
  delay: (ms: number) => new Promise((resolve) => setTimeout(resolve, ms)),
}
`,
    language: 'typescript',
    category: 'testing',
    confidence: 90,
    description: 'Vitest setup file with mocks',
  }, {
    path: 'tests/example.test.ts',
    content: `// =============================================================================
// EXAMPLE TEST FILE
// =============================================================================
// Generated by Orion - replace with your actual tests

import { describe, it, expect, vi } from 'vitest'

describe('Example Test Suite', () => {
  it('should pass a basic test', () => {
    expect(1 + 1).toBe(2)
  })

  it('should work with async operations', async () => {
    const result = await Promise.resolve('hello')
    expect(result).toBe('hello')
  })

  it('should mock functions', () => {
    const mockFn = vi.fn().mockReturnValue('mocked')
    expect(mockFn()).toBe('mocked')
    expect(mockFn).toHaveBeenCalledTimes(1)
  })
})

// Example component test (for React)
// import { render, screen } from '@testing-library/react'
// import { MyComponent } from '@/components/MyComponent'
//
// describe('MyComponent', () => {
//   it('should render correctly', () => {
//     render(<MyComponent />)
//     expect(screen.getByText('Hello')).toBeInTheDocument()
//   })
// })
`,
    language: 'typescript',
    category: 'testing',
    confidence: 85,
    description: 'Example test file template',
  }]
}

/**
 * Generate Playwright E2E setup
 */
function generatePlaywrightSetup(): GeneratedFile[] {
  return [{
    path: 'playwright.config.ts',
    content: `// =============================================================================
// PLAYWRIGHT E2E CONFIGURATION
// =============================================================================
// Generated by Orion

import { defineConfig, devices } from '@playwright/test'

export default defineConfig({
  testDir: './e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  
  use: {
    baseURL: 'http://localhost:3000',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
    {
      name: 'Mobile Chrome',
      use: { ...devices['Pixel 5'] },
    },
  ],

  webServer: {
    command: 'npm run dev',
    url: 'http://localhost:3000',
    reuseExistingServer: !process.env.CI,
  },
})
`,
    language: 'typescript',
    category: 'testing',
    confidence: 95,
    description: 'Playwright E2E configuration',
  }, {
    path: 'e2e/example.spec.ts',
    content: `// =============================================================================
// EXAMPLE E2E TEST
// =============================================================================
// Generated by Orion

import { test, expect } from '@playwright/test'

test.describe('Homepage', () => {
  test('should load the homepage', async ({ page }) => {
    await page.goto('/')
    
    // Check page title
    await expect(page).toHaveTitle(/.*/)
    
    // Check basic content
    await expect(page.locator('body')).toBeVisible()
  })

  test('should have working navigation', async ({ page }) => {
    await page.goto('/')
    
    // Example: check for a link and click it
    // const link = page.getByRole('link', { name: 'About' })
    // await link.click()
    // await expect(page).toHaveURL(/about/)
  })
})

test.describe('Authentication', () => {
  test('should show login button when not authenticated', async ({ page }) => {
    await page.goto('/')
    
    // Replace with your actual login button selector
    // const loginButton = page.getByRole('button', { name: /sign in/i })
    // await expect(loginButton).toBeVisible()
  })
})
`,
    language: 'typescript',
    category: 'testing',
    confidence: 85,
    description: 'Example Playwright E2E test',
  }]
}

